### ISSUE TITLE
DynamoDB test fails with single-thread executor.

### ISSUE THREAD

**Issue by afck** [linera-io/linera-protocol#1159] opened 2023-10-26 09:59 UTC
To reproduce, run:

```bash
docker run --rm -d --name local-dynamodb -p 8000:8000/tcp amazon/dynamodb-local
LINERA_SERVER_TOKIO_THREADS="1" AWS_REGION=us-east-1 AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test LOCALSTACK_ENDPOINT=http://localhost:8000/  cargo test --features aws -- test_wasm_end_to_end_matching_engine --ignored
```

~It looks like [this `await` doesn't return](https://github.com/linera-io/linera-protocol/blob/da1805ddf694800118e96c1789fb94cca3a246a2/linera-views/src/dynamo_db.rs#L542). Callers (indirect) are `coherently_resolve_transactions` and `write_batch`, [and ultimately `handle_block_proposal` via `write_values`](https://github.com/linera-io/linera-protocol/blob/da1805ddf694800118e96c1789fb94cca3a246a2/linera-core/src/worker.rs#L1017).~

**Comment by ma2bd** [comment] 2023-10-27 11:23
We may want to start by upgrading https://crates.io/crates/aws-sdk-dynamodb

**Comment by ma2bd** [comment] 2023-10-27 11:26
Could also be related to https://github.com/awslabs/aws-sdk-rust/issues/611

**Comment by afck** [comment] 2023-11-08 10:18
The `aws-*` dependencies have been updated, but the test still fails in the same way.

**Comment by jvff** [comment] 2023-12-12 02:27
I believe I managed to reproduce this on my laptop (with and and without the single thread executor), but it seems to not appear if I increase some timeouts by an order of magnitude:

- https://github.com/linera-io/linera-protocol/blob/de0349546a19b03eccb424a12d2d91a4832bae2b/linera-service/src/cli_wrappers/wallet.rs#L41
- https://github.com/linera-io/linera-protocol/blob/de0349546a19b03eccb424a12d2d91a4832bae2b/linera-service/src/cli_wrappers/wallet.rs#L141-L142
- https://github.com/linera-io/linera-protocol/blob/de0349546a19b03eccb424a12d2d91a4832bae2b/linera-service/src/linera.rs#L611
- https://github.com/linera-io/linera-protocol/blob/de0349546a19b03eccb424a12d2d91a4832bae2b/linera-service/src/linera.rs#L615
- https://github.com/linera-io/linera-protocol/blob/de0349546a19b03eccb424a12d2d91a4832bae2b/linera-service/src/proxy.rs#L35
- https://github.com/linera-io/linera-protocol/blob/de0349546a19b03eccb424a12d2d91a4832bae2b/linera-service/src/proxy.rs#L39

@afck, could you check if the error is still reproducible with the increased timeouts?

**Comment by afck** [comment] 2023-12-12 19:55
@jvff: Thanks! I can confirm that this passes for me.

**Comment by MathieuDutSik** [comment] 2024-01-29 09:49
I think we can close the issue since the bug has been addressed.

**Closed by MathieuDutSik** 2024-01-29 09:49 UTC
Labels: bug
